on: workflow_dispatch
name: testando
jobs:
  testando01:
    runs-on: ubuntu-latest
    steps:
      - name: step-01
        run: |
          sleep 10
          while true                                                                                                                                                                                                  1 
            do
              exit "$(date +%N)%2" | bc
            done

  
